global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'localrank-django'
    static_configs:
      - targets: ['localrank-web:8000']
    metrics_path: /metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'django-probe'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['localrank-web:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

rule_files:
  - "alert.rules.yml" 